INCLUDE(InstallRequiredSystemLibraries)
SET(CPACK_PACKAGE_DESCRIPTION "Ride")
SET(CPACK_PACKAGE_VENDOR "madeso")

SET(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_INSTALL_PREFIX}")

MESSAGE(STATUS "Setting cpack paths to ${PROJECT_SOURCE_DIR}/gfx/install/")
SET(CPACK_DMG_BACKGROUND_IMAGE "${PROJECT_SOURCE_DIR}/gfx/install/dmg-install.png")
SET(CPACK_DMG_DS_STORE "${PROJECT_SOURCE_DIR}/gfx/install/ds_store")

IF(${APPLE})
  SET(CPACK_GENERATOR DragNDrop)
ENDIF()

# wix setup
SET(CPACK_WIX_UPGRADE_GUID "AF8E1C30-9FE1-4AF0-A9B8-DCC9ECD57CF6")
SET(CPACK_WIX_LICENSE_RTF "${PROJECT_SOURCE_DIR}/LICENSE.rtf")
SET(CPACK_WIX_PRODUCT_ICON "${PROJECT_SOURCE_DIR}/gfx/logo/icon.ico")
SET(CPACK_WIX_UI_BANNER "${PROJECT_SOURCE_DIR}/gfx/install/wix-banner.png")
SET(CPACK_WIX_UI_DIALOG "${PROJECT_SOURCE_DIR}/gfx/install/wix-dialog.png")

IF(${WIN32})
  SET(CPACK_GENERATOR WIX)
ENDIF()

MESSAGE(STATUS "Install generators are ${CPACK_GENERATOR}")

# this must always be last
INCLUDE(CPack)
