#ifndef RIDE_RIDE_RESOURCES_ICON_H
#define RIDE_RIDE_RESOURCES_ICON_H

#include "icons/edit_copy.xpm"
#include "icons/edit_cut.xpm"
#include "icons/edit_make_lowercase.xpm"
#include "icons/edit_make_uppercase.xpm"
#include "icons/edit_paste.xpm"
#include "icons/edit_redo.xpm"
#include "icons/edit_tab_add.xpm"
#include "icons/edit_tab_remove.xpm"
#include "icons/edit_undo.xpm"
#include "icons/file_normal.xpm"
#include "icons/file_warning.xpm"
#include "icons/folder_error.xpm"
#include "icons/folder_normal.xpm"
#include "icons/folder_warning.xpm"
#include "icons/project_bench.xpm"
#include "icons/project_build.xpm"
#include "icons/project_clean.xpm"
#include "icons/project_debug.xpm"
#include "icons/project_doc.xpm"
#include "icons/project_rebuild.xpm"
#include "icons/project_run.xpm"
#include "icons/project_stop.xpm"
#include "icons/project_test.xpm"
#include "icons/project_update.xpm"

#include "icons/edit_file_properties.xpm"
#include "icons/file_settings.xpm"
#include "icons/file_quit.xpm"
#include "icons/project_settings.xpm"

#include "icons/create_app.xpm"
#include "icons/create_library.xpm"

#include "icons/icon_ac_function.xpm"
#include "icons/icon_ac_crate.xpm"
#include "icons/icon_ac_let.xpm"
#include "icons/icon_ac_struct.xpm"
#include "icons/icon_ac_structfield.xpm"
#include "icons/icon_ac_keyword.xpm"
#include "icons/icon_ac_snippet.xpm"

#endif  // RIDE_RIDE_RESOURCES_ICON_H