cd %APPVEYOR_BUILD_FOLDER%
mkdir build

cd %APPVEYOR_BUILD_FOLDER%\build
cmake -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\install-dist\ -DPROTOBUF_SRC_ROOT_FOLDER=%APPVEYOR_BUILD_FOLDER%\install-dist\proto\ -DwxWidgets_ROOT_DIR=%APPVEYOR_BUILD_FOLDER%\install-dist\wx\ -DRIDE_BUILD_COMMIT=%APPVEYOR_REPO_COMMIT% -DRIDE_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER% -DRIDE_BUILD_BRANCH=%APPVEYOR_REPO_BRANCH% -DRIDE_BUILD_REPO=%APPVEYOR_REPO_NAME% $CMAKEOSXARG ..
