#!/bin/bash
set -ev

CMAKEOSXARG=""

if [ "$TRAVIS_OS_NAME" = "osx" ]; then
  CMAKEOSXARG="-DCMAKE_OSX_DEPLOYMENT_TARGET=10.10"
fi

cmake -DCMAKE_PREFIX_PATH=$TRAVIS_BUILD_DIR/deps/ -DwxWidgets_CONFIG_OPTIONS="--prefix=$TRAVIS_BUILD_DIR/deps/" $CMAKEOSXARG .
