#!/bin/bash
set -ev

cd $TRAVIS_BUILD_DIR
# mkdir build
# cd build
cmake -DBUILD_USE_CLANG_TIDY=OFF -DBUILD_USE_CLANG_FORMAT=OFF -DBUILD_USE_CPPLINT=OFF -DBUILD_USE_DOXYGEN=OFF -DBUILD_USE_DOXYGEN_GLOBAL=OFF -DBUILD_USE_CPPCHECK=OFF -DBUILD_USE_INCLUDECHECK=OFF -DUSE_WXWIDGETS_LEGACY_FINDTEXT=ON -DUSE_CPP_AS_RUST=ON .
