// Copyright (2015) Gustav

#ifndef RIDE_RIDE_COMPILER_SETTINGS_IN_H_
#define RIDE_RIDE_COMPILER_SETTINGS_IN_H_

#cmakedefine USE_WXWIDGETS_LEGACY_FINDTEXT

#cmakedefine USE_CPP_AS_RUST

#cmakedefine RIDE_OS_APPLE

#cmakedefine RIDE_WXWIDGETS_USE_NEW_GO_HOME_END

#endif  // RIDE_RIDE_COMPILER_SETTINGS_IN_H_
