// Copyright (2015) Gustav

#ifndef RIDE_VERSION_H_
#define RIDE_VERSION_H_

#define VER_FILEVERSION 1, 0, 0, 0
#define VER_FILEVERSION_STR "1.0.0.0\0"

#define VER_PRODUCTVERSION 1, 0, 0, 0
#define VER_PRODUCTVERSION_STR "1.0\0"

#define VER_COMPANYNAME_STR "madeso"
#define VER_FILEDESCRIPTION_STR "Rust IDE"
#define VER_INTERNALNAME_STR VER_FILEDESCRIPTION_STR
#define VER_LEGALCOPYRIGHT_STR "Copyright C 2014 madeso"  // NOLINT(*)
#define VER_LEGALTRADEMARKS1_STR "All Rights Reserved"
#define VER_LEGALTRADEMARKS2_STR VER_LEGALTRADEMARKS1_STR
#define VER_ORIGINALFILENAME_STR "ride.exe"
#define VER_PRODUCTNAME_STR "Ride"

#define VER_COMPANYDOMAIN_STR "madeso.me"

#endif  // RIDE_VERSION_H_
